import Config

config :doc_republisher,
  exit_on_failure: true,
  log_file: "doc_republisher.log",
  packages: [
    {:atecc508a, github: "nerves-hub/atecc508a", versions: ">= 1.4.0"},
    # {:beam_benchmarks, github: "fhunleth/beam_benchmarks"},
    {:beam_notify, github: "nerves-networking/beam_notify"},
    # {:blue_heron, github: "blue-heron/blue_heron"},
    # {:blue_heron_transport_uart, github: "blue-heron/blue_heron_transport_uart"},
    # {:blue_heron_transport_usb, github: "blue-heron/blue_heron_transport_usb"},
    {:bmp280, github: "elixir-sensors/bmp280", versions: ">= 0.2.12"},
    # {:busybox, github: "nerves-networking/elixir_busybox"},
    # {:cerlc, github: "mdsebald/cerlc"},
    {:circuits_gpio, github: "elixir-circuits/circuits_gpio"},
    {:circuits_i2c, github: "elixir-circuits/circuits_i2c"},
    {:circuits_sim, github: "elixir-circuits/circuits_sim"},
    {:circuits_spi, github: "elixir-circuits/circuits_spi"},
    {:circuits_uart, github: "elixir-circuits/circuits_uart"},
    {:circular_buffer, github: "elixir-toniq/circular_buffer", versions: ">= 0.4.2"},
    {:delux, github: "elixir-circuits/delux"},
    # {:fortune, github: "fhunleth/elixir-fortune"},
    # {:fwup, github: "ConnorRigby/elixir-fwup"},
    {:input_event, github: "nerves-web-kiosk/input_event"},
    {:intel_hex, github: "fhunleth/intel_hex"},
    {:interactive_cmd, github: "fhunleth/interactive_cmd"},
    # {:kiosk_system_rpi4, github: "nerves-web-kiosk/kiosk_system_rpi4"},
    # {:kiosk_system_rpi5, github: "nerves-web-kiosk/kiosk_system_rpi5"},
    {:mdns_lite, github: "nerves-networking/mdns_lite"},
    {:midi_synth, github: "fhunleth/midi_synth", versions: ">= 0.4.2"},
    # {:mobius, github: "mobius-home/mobius"},
    {:muontrap, github: "fhunleth/muontrap"},
    # {:nerves_hub_ca_store, github: "nerves-hub/nerves_hub_ca_store"},
    # {:nerves_hub_cli, github: "nerves-hub/nerves_hub_cli"},
    # {:nerves_hub_core, github: "nerves-hub/nerves_hub_core"},
    # {:nerves_hub_link, github: "nerves-hub/nerves_hub_link"},
    # {:nerves_hub_link_common, github: "nerves-hub/nerves_hub_link_common"},
    # {:nerves_hub_user_api, github: "nerves-hub/nerves_hub_user_api"},
    {:nerves_key, github: "nerves-hub/nerves_key", versions: ">= 1.3.0"},
    {:nerves_key_pkcs11, github: "nerves-hub/nerves_key_pkcs11"},
    # {:nerves_leds, github: "nerves-project/nerves_leds"},
    # {:nerves_livebook, github: "nerves-livebook/nerves_livebook"},
    # {:nerves_network, github: "nerves-project/nerves_network"},
    # {:nerves_network_interface, github: "nerves-project/nerves_network_interface"},
    # {:nerves_runtime_shell, github: "nerves-project/nerves_runtime_shell"},
    # {:nerves_system, github: "nerves-project/nerves_system"},
    # {:nerves_system_mangopi_mq_pro, github: "nerves-project/nerves_system_mangopi_mq_pro"},
    # {:nerves_system_npi_imx6ull, github: "fhunleth/nerves_system_npi_imx6ull"},
    # {:nerves_system_qemu_arm, github: "nerves-project/nerves_system_qemu_arm"},
    # {:nerves_system_rpi0_2, github: "fhunleth/nerves_system_rpi0_2"},
    {:nerves_time, github: "nerves-time/nerves_time"},
    {:nerves_time_rtc_abracon, github: "nerves-time/nerves_time_rtc_abracon"},
    {:nerves_time_rtc_ds3231, github: "nerves-time/nerves_time_rtc_ds3231"},
    {:nerves_time_rtc_nxp, github: "nerves-time/nerves_time_rtc_nxp"},
    {:nerves_time_zones, github: "nerves-time/nerves_time_zones"},
    # {:nerves_toolchain, github: "nerves-project/nerves_toolchain"},
    # {:nerves_toolchain_aarch64_nerves_linux_musl, github: "nerves-project/toolchains"},
    # {:nerves_toolchain_armv7_nerves_linux_musleabihf, github: "nerves-project/toolchains"},
    # {:nerves_toolchain_riscv64_nerves_linux_musl, github: "nerves-project/toolchains"},
    {:one_dhcpd, github: "fhunleth/one_dhcpd"},
    # {:picam, github: "elixir-vision/picam"},
    {:pinout, github: "cavocado/pinout"},
    {:qmi, github: "nerves-networking/qmi"},
    # {:rpi_fb_capture, github: "pappersverk/rpi_fb_capture"},
    {:sht4x, github: "elixir-sensors/sht4x"},
    {:tablet, github: "fhunleth/tablet"},
    {:toolshed, github: "elixir-toolshed/toolshed"},
    {:vintage_net, github: "nerves-networking/vintage_net"},
    {:vintage_net_bridge, github: "nerves-networking/vintage_net_bridge"},
    {:vintage_net_direct, github: "nerves-networking/vintage_net_direct"},
    {:vintage_net_ethernet, github: "nerves-networking/vintage_net_ethernet"},
    {:vintage_net_mobile, github: "nerves-networking/vintage_net_mobile"},
    {:vintage_net_qmi, github: "nerves-networking/vintage_net_qmi"},
    {:vintage_net_wifi, github: "nerves-networking/vintage_net_wifi"},
    {:vintage_net_wizard, github: "nerves-networking/vintage_net_wizard"},
    {:zoneinfo, github: "nerves-time/zoneinfo"}
  ]
