import Config

config :doc_republisher,
  exit_on_failure: true,
  log_file: "doc_republisher.log",
  packages: [
    {:alarmist, github: "smartrent/alarmist"},
    {:atecc508a, github: "nerves-hub/atecc508a", versions: ">= 1.4.0"},
    # {:beam_benchmarks, github: "fhunleth/beam_benchmarks"},
    {:beam_notify, github: "nerves-networking/beam_notify"},
    # {:blue_heron, github: "blue-heron/blue_heron"},
    # {:blue_heron_transport_uart, github: "blue-heron/blue_heron_transport_uart"},
    # {:blue_heron_transport_usb, github: "blue-heron/blue_heron_transport_usb"},
    {:bmp280, github: "elixir-sensors/bmp280", versions: ">= 0.2.12"},
    # {:busybox, github: "nerves-networking/elixir_busybox"},
    # {:cerlc, github: "mdsebald/cerlc"},
    {:circuits_gpio, github: "elixir-circuits/circuits_gpio"},
    {:circuits_i2c, github: "elixir-circuits/circuits_i2c"},
    {:circuits_sim, github: "elixir-circuits/circuits_sim"},
    {:circuits_spi, github: "elixir-circuits/circuits_spi"},
    {:circuits_uart, github: "elixir-circuits/circuits_uart"},
    {:circular_buffer, github: "elixir-toniq/circular_buffer", versions: ">= 0.4.2"},
    {:delux, github: "elixir-circuits/delux"},
    # {:fortune, github: "fhunleth/elixir-fortune"},
    {:fwup, github: "ConnorRigby/elixir-fwup", versions: ">= 1.0.1"},
    {:input_event, github: "nerves-web-kiosk/input_event"},
    {:intel_hex, github: "fhunleth/intel_hex"},
    {:interactive_cmd, github: "fhunleth/interactive_cmd"},
    # {:kiosk_system_rpi4, github: "nerves-web-kiosk/kiosk_system_rpi4"},
    # {:kiosk_system_rpi5, github: "nerves-web-kiosk/kiosk_system_rpi5"},
    {:mdns_lite, github: "nerves-networking/mdns_lite"},
    {:midi_synth, github: "fhunleth/midi_synth", versions: ">= 0.4.2"},
    # {:mobius, github: "mobius-home/mobius"},
    {:muontrap, github: "fhunleth/muontrap"},
    {:nerves, github: "nerves-project/nerves"},
    {:nerves_bootstrap, github: "nerves-project/nerves_bootstrap"},
    {:nerves_discovery, github: "nerves-networking/nerves_discovery"},
    {:nerves_firmware_ssh, github: "nerves-project/nerves_firmware_ssh"},
    # {:nerves_hub_cli, github: "nerves-hub/nerves_hub_cli"},
    {:nerves_hub_link, github: "nerves-hub/nerves_hub_link"},
    {:nerves_key, github: "nerves-hub/nerves_key", versions: ">= 1.3.0"},
    {:nerves_key_pkcs11, github: "nerves-hub/nerves_key_pkcs11"},
    # {:nerves_leds, github: "nerves-project/nerves_leds"},
    # {:nerves_livebook, github: "nerves-livebook/nerves_livebook"},
    {:nerves_logging, github: "nerves-project/nerves_logging"},
    {:nerves_motd, github: "nerves-project/nerves_motd"},
    {:nerves_pack, github: "nerves-project/nerves_pack"},
    {:nerves_runtime, github: "nerves-project/nerves_runtime"},
    # {:nerves_runtime_shell, github: "nerves-project/nerves_runtime_shell"},
    {:nerves_ssh, github: "nerves-project/nerves_ssh"},
    # {:nerves_system, github: "nerves-project/nerves_system"},
    # {:nerves_system_bbb, github: "nerves-project/nerves_system_bbb"},
    # {:nerves_system_br, github: "nerves-project/nerves_system_br"},
    # {:nerves_system_grisp2, github: "nerves-project/nerves_system_grisp2"},
    # {:nerves_system_linter, github: "nerves-project/nerves_system_linter"},
    # {:nerves_system_mangopi_mq_pro, github: "nerves-project/nerves_system_mangopi_mq_pro"},
    # {:nerves_system_npi_imx6ull, github: "fhunleth/nerves_system_npi_imx6ull"},
    # {:nerves_system_osd32mp1, github: "nerves-project/nerves_system_osd32mp1"},
    # {:nerves_system_qemu_arm, github: "nerves-project/nerves_system_qemu_arm"},
    # {:nerves_system_qemu_aarch64, github: "nerves-project/nerves_system_qemu_aarch64"},
    # {:nerves_system_rpi, github: "nerves-project/nerves_system_rpi"},
    # {:nerves_system_rpi0, github: "nerves-project/nerves_system_rpi0"},
    # {:nerves_system_rpi0_2, github: "fhunleth/nerves_system_rpi0_2"},
    # {:nerves_system_rpi2, github: "nerves-project/nerves_system_rpi2"},
    # {:nerves_system_rpi3, github: "nerves-project/nerves_system_rpi3"},
    # {:nerves_system_rpi3a, github: "nerves-project/nerves_system_rpi3a"},
    # {:nerves_system_rpi4, github: "nerves-project/nerves_system_rpi4"},
    # {:nerves_system_rpi5, github: "nerves-project/nerves_system_rpi5"},
    # {:nerves_system_vultr, github: "nerves-project/nerves_system_vultr"},
    # {:nerves_system_x86_64, github: "nerves-project/nerves_system_x86_64"},
    {:nerves_time, github: "nerves-time/nerves_time"},
    {:nerves_time_rtc_abracon, github: "nerves-time/nerves_time_rtc_abracon"},
    {:nerves_time_rtc_ds3231, github: "nerves-time/nerves_time_rtc_ds3231"},
    {:nerves_time_rtc_nxp, github: "nerves-time/nerves_time_rtc_nxp"},
    {:nerves_time_zones, github: "nerves-time/nerves_time_zones"},
    # {:nerves_toolchain, github: "nerves-project/nerves_toolchain"},
    # {:nerves_toolchain_aarch64_nerves_linux_musl, github: "nerves-project/toolchains"},
    # {:nerves_toolchain_armv7_nerves_linux_musleabihf, github: "nerves-project/toolchains"},
    # {:nerves_toolchain_ctng, github: "nerves-project/toolchains"},
    # {:nerves_toolchain_riscv64_nerves_linux_musl, github: "nerves-project/toolchains"},
    {:nerves_uevent, github: "nerves-project/nerves_uevent"},
    {:one_dhcpd, github: "fhunleth/one_dhcpd"},
    # {:picam, github: "elixir-vision/picam"},
    {:pinout, github: "cavocado/pinout"},
    {:property_table, github: "nerves-project/property_table"},
    {:qmi, github: "nerves-networking/qmi"},
    {:ramoops_logger, github: "nerves-project/ramoops_logger"},
    {:ring_logger, github: "nerves-project/ring_logger"},
    # {:rpi_fb_capture, github: "pappersverk/rpi_fb_capture"},
    {:shoehorn, github: "nerves-project/shoehorn"},
    {:sht4x, github: "elixir-sensors/sht4x"},
    {:ssh_subsystem_fwup, github: "nerves-project/ssh_subsystem_fwup"},
    {:tablet, github: "fhunleth/tablet"},
    {:toolshed, github: "elixir-toolshed/toolshed"},
    {:uboot_env, github: "nerves-project/uboot_env"},
    {:vintage_net, github: "nerves-networking/vintage_net"},
    {:vintage_net_bridge, github: "nerves-networking/vintage_net_bridge"},
    {:vintage_net_direct, github: "nerves-networking/vintage_net_direct"},
    {:vintage_net_ethernet, github: "nerves-networking/vintage_net_ethernet"},
    {:vintage_net_mobile, github: "nerves-networking/vintage_net_mobile"},
    {:vintage_net_qmi, github: "nerves-networking/vintage_net_qmi"},
    {:vintage_net_wifi, github: "nerves-networking/vintage_net_wifi"},
    {:vintage_net_wireguard, github: "nerves-networking/vintage_net_wireguard"},
    {:vintage_net_wizard, github: "nerves-networking/vintage_net_wizard"},
    {:zoneinfo, github: "nerves-time/zoneinfo"}
  ]
